Next try

diff --git a/bin/create_sys_image b/bin/create_sys_image
--- a/bin/create_sys_image
+++ b/bin/create_sys_image
@@ -1,18 +1,5 @@
 #!/bin/bash -eu
 
-update=false
-if [[ $# -gt 0 ]]; then
-    if [[ $1 != "--update" ]]; then
-        echo "Invalid parameter! Use:"
-        echo "./create_sys_image"
-        echo "or"
-        echo "./create_sys_image --update"
-        exit 1
-    else
-        update=true
-    fi
-fi
-
 if [[ $(basename $(pwd)) == "bin" ]]; then
     cd ..
 fi
@@ -22,20 +9,15 @@ mkdir -p output
 export MPLBACKEND=qt5agg
 export JULIA_PKG_SERVER_REGISTRY_PREFERENCE="eager"
 
-if [[ $HOSTNAME == "ufryzen" || $HOSTNAME == "framework" ]]; then
-    export NO_MTK=true
-fi
-
 if ! command -v juliaup &> /dev/null; then
-    echo "Please install the Julia installer 'juliaup'!"
-    echo "See: https://github.com/JuliaLang/juliaup"
+    echo "Juliaup not found. Please run: ./install"
     exit 1
 fi
 
 # if julia is not installed, install Julia 1.11
 if ! command -v julia &> /dev/null; then
-    juliaup add 1.11
-    juliaup default 1.11
+    echo "Julia not found. Please run: ./install"
+    exit 1
 fi
 
 julia_version=$(julia --version | awk '{print($3)}')
@@ -45,10 +27,10 @@ if [[ $julia_major == "1.1" ]]; then
 fi
 
 # if the current julia version is older than 1.10, exit
-if [[ $julia_major == "1.10" ]] || [[ $julia_major == "1.11" ]]; then
+if [[ $julia_major == "1.11" ]] || [[ $julia_major == "1.12" ]]; then
     echo OK
 else
-    echo "The current Julia version is too old, installing Julia 1.11!"
+    echo "The current Julia version is not supported, installing Julia 1.11!"
     juliaup add 1.11
     juliaup default 1.11
 fi
@@ -95,48 +77,15 @@ fi
 if test -f "kps-image-${julia_major}-${branch}.so"; then
     mv bin/kps-image-${julia_major}-${branch}.so kps-image-${julia_major}-${branch}.so.bak
 fi
-julia --startup-file=no -e "using Pkg; Pkg.add(\"TestEnv\")"
-
-if [[ $update == true ]]; then
-    echo "Updating packages..."
-    export JULIA_PKG_SERVER_REGISTRY_PREFERENCE="eager"
-    if test -f "Manifest.toml"; then
-        mv Manifest.toml Manifest.toml.bak
-    fi
-    if [[ $julia_major == "1.10" ]]; then
-        if test -f "Manifest-v1.10.toml"; then
-            mv Manifest-v1.10.toml Manifest-v1.10.toml.bak
-        fi
-    else
-        if test -f "Manifest-v1.11.toml"; then
-            mv Manifest-v1.11.toml Manifest-v1.11.toml.bak
-        fi
-    fi
-    julia --startup-file=no --pkgimages=no --project -e "using TestEnv; TestEnv.activate(); using Pkg; Pkg.add(\"PyCall\"); Pkg.build(\"PyCall\")"
-    if [[ $PYTHON == "" ]]; then
-        julia --startup-file=no --pkgimages=no --project -e "using TestEnv; TestEnv.activate(); using Pkg; Pkg.add(\"Conda\"); using Conda; Conda.add(\"matplotlib\"); using ControlPlots"
-    fi
-    julia --startup-file=no --pkgimages=no --project -e "using Pkg; Pkg.update()"
-    if [[ $julia_major == "1.10" ]]; then
-        mv Manifest.toml Manifest-v1.10.toml
-    else
-        mv Manifest.toml Manifest-v1.11.toml
-    fi
+if [[ $julia_major == "1.10" ]]; then
+    cp Manifest-v1.10.toml.default Manifest-v1.10.toml
+    echo "Using Manifest-v1.10.toml.default ..."        
 else
-    if [[ $julia_major == "1.10" ]]; then
-        cp Manifest-v1.10.toml.default Manifest-v1.10.toml
-        echo "Using Manifest-v1.10.toml.default ..."        
-    else
-        cp Manifest-v1.11.toml.default Manifest-v1.11.toml
-        echo "Using Manifest-v1.11.toml.default ..."
-    fi
+    cp Manifest-v1.11.toml.default Manifest-v1.11.toml
+    echo "Using Manifest-v1.11.toml.default ..."
 fi
-if [[ $update == true ]]; then
-    julia --startup-file=no --pkgimages=no --project -e "include(\"./test/create_sys_image.jl\");"
-else
-    julia --startup-file=no --pkgimages=no --project -e "using Pkg; Pkg.instantiate();"
-    julia --startup-file=no --pkgimages=no --project -e "using TestEnv; TestEnv.activate(); include(\"./test/create_sys_image.jl\");"
-fi
+julia --startup-file=no --pkgimages=no --project -e "using Pkg; Pkg.instantiate();"
+julia --startup-file=no --pkgimages=no --project=test -e "include(\"./test/create_sys_image.jl\")"
 
 if [[ $branch != "" ]]; then
     SOFILE="bin/kps-image-${julia_major}-${branch}.so"
@@ -154,5 +103,5 @@ if [ -d src ]; then
     cd ..
 fi
 julia --project -J bin/kps-image-${julia_major}-${branch}.so -e "using KiteUtils, KiteControllers"
-julia --project -J bin/kps-image-${julia_major}-${branch}.so -e "using TestEnv; TestEnv.activate(); using ControlPlots, NativeFileDialog"
-julia --project -J bin/kps-image-${julia_major}-${branch}.so -e "using Pkg; Pkg.update()"
+julia --project=test -J bin/kps-image-${julia_major}-${branch}.so -e "using ControlPlots, NativeFileDialog"
+julia --project -J bin/kps-image-${julia_major}-${branch}.so -e "using Pkg; Pkg.instantiate()"
